name: Deploy React App
on:
  push:
    branches:
      - master
    #path-ignore:
    #  - '.github/workflows/*'
jobs:
  my_first_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test

  my_lint:
    runs-on: ubuntu-latest
    needs: my_first_tests
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  
  my_build:
    runs-on: ubuntu-latest
    needs: my_lint
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying ...
